"""Initial migration

Revision ID: 55ef25320f92
Revises: 409b4b4ca3fb
Create Date: 2025-11-13 05:52:42.751372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ef25320f92'
down_revision = '409b4b4ca3fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('full_care_instructions', sa.Text(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('latin_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('plant_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('lifespan',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('light',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('difficulty',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('water_frequency',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('temperature',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Text(),
               nullable=False)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=60),
               existing_nullable=False)
        batch_op.drop_column('username')
        batch_op.drop_column('registration_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('date')
        batch_op.drop_column('name')

    with op.batch_alter_table('plant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.alter_column('temperature',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('water_frequency',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('difficulty',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('light',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('lifespan',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('plant_type',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('latin_name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('full_care_instructions')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
